project:
  type: website
  resources:
    - "image_title_block.jpg"

website:
  title: "Home"
  navbar:
    left:
      - icon: github
        href: https://github.com/durraniu/30_day_map_challenge_2024
    right:
      - href: https://umairdurrani.com/
        text: About
        target: _blank
    
format:
  html:
    theme: lux
    css: styles.css
    df-print: paged



