project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - icon: github
        href: https://github.com/
    right:
      - href: https://umairdurrani.com/
        text: About
        target: _blank
    
format:
  html:
    theme: lux
    css: styles.scss
    df-print: paged



